### ISSUE TITLE
ciao-cli node list --compute shows 3 nodes on a 2 compute node network

### ISSUE THREAD

**Issue by markdryan** [01org/ciao#1187] opened 2017-02-21 10:35 UTC
I installed ciao on a four node cluster using the ansible scripts and ran a

ciao-cli node list --compute.

I was surprised to see 3 compute nodes

```
)$ ciao-cli node list -compute 
Compute Node 1
	UUID: 3af60b27-0be9-48d7-936c-ce783bd4202b
	Status: READY
	Load: 0
	Available/Total memory: 15482/15933 MB
	Available/Total disk: 93508/101222 MB
	Total Instances: 0
		Running Instances: 0
		Pending Instances: 0
		Paused Instances: 0
Compute Node 2
	UUID: 6444e15c-d93a-4faa-b573-c7fe2335b260
	Status: READY
	Load: 0
	Available/Total memory: 15537/15933 MB
	Available/Total disk: 93911/101222 MB
	Total Instances: 0
		Running Instances: 0
		Pending Instances: 0
		Paused Instances: 0
Compute Node 3
	UUID: b52f6d1a-f4a1-4009-9a9d-b426621ba685
	Status: READY
	Load: 0
	Available/Total memory: 15488/15933 MB
	Available/Total disk: 93348/101222 MB
	Total Instances: 0
		Running Instances: 0
		Pending Instances: 0
		Paused Instances: 0
```

The second node is the network node as we can see from the controller logs

```
  node_uuid: 6444e15c-d93a-4faa-b573-c7fe2335b260
  node_type: network_node
```

I verified that the launcher running on the network node was not running in dual mode.

$ ./ciao-cert --dump /etc/pki/ciao/cert-NetworkingAgent-localhost.pem

```
Certificate:	/etc/pki/ciao/cert-NetworkingAgent-localhost.pem
Organization:	Example Inc.
Is CA:		false
Validity:	2017-02-21 10:15:15 +0000 UTC to 2018-02-21 10:15:15 +0000 UTC
For role:	NetworkingAgent
For host:	localhost
Private key:	RSA PRIVATE KEY
```

**Comment by tpepper** [comment] 2017-02-21 23:05
I'm reproducing this also

**Comment by tpepper** [comment] 2017-02-21 23:52
Looks like the controller treats all nodes sending stats frames as compute nodes.  Network nodes send stats to report their capacity for landing CNCI's.  This doesn't look easy to fix.

**Comment by tpepper** [comment] 2017-02-23 16:29
This is a duplicate of issue #780 and relates to issue #623 .

**Closed** 2017-02-23 16:30 UTC
Labels: bug, ciao-cli, ciao-controller, in progress
