### ISSUE TITLE
Issue with "pending" status VMs

### ISSUE THREAD

**Issue by obedmr** [01org/ciao#75] opened 2016-04-28 16:39 UTC
I got some issues when trying to overpass limits of my cloud. Below are the steps I followed.

**1. First, let's create 100 VMs**
```bash
root@clr-ciao01 ~ # ciao-cli -launch-instances -workload e35ed972-c46c-4aad-a1e7-ef103ae079a2 -instances 100
Created new instance: ecc6d3df-6b59-42ee-b775-c4e74828d41d
Created new instance: fdaa92be-4dc8-42b7-bfb0-5c7d7f429bb1
Created new instance: efc2ca9f-eae2-4801-9474-c60a170381f6
.
.
.
```
**2. After some reasonable time, let's check how many are running**
```bash
root@clr-ciao01 ~ # ciao-cli -list-instances | grep running | wc -l
99
```
**3. It seems like there's one missing**
```bash
root@clr-ciao01 ~ # ciao-cli -list-instances | grep Status | grep -v running
        Status: exited
```
**4. Now, let's try to overpass the limit of my cloud 
  (I got the "Unable to dispatch: Cloud is full" message 
  in the scheduler which should be normal)**
```bash
root@clr-ciao01 ~ # ciao-cli -launch-instances -workload e35ed972-c46c-4aad-a1e7-ef103ae079a2 -instances 50
Created new instance: 59238570-8943-4b7a-ad04-7a260b8a1073
Created new instance: f13312c2-062a-4db7-88a6-75bbf8f82adc
Created new instance: 4c9632c0-0163-4410-9aae-a68ba6ec7789
.
.
.
```
**5. Let's review the status of not-created instances**
```bash
root@clr-ciao01 ~ # ciao-cli -list-instances | grep Status | grep -v running
        Status: pending
        Status: pending
        Status: pending
        Status: exited
        .
        .
```
**6. We have 24, 23 on pending and 1 excited**
```bash
root@clr-ciao01 ~ # ciao-cli -list-instances | grep Status | grep -v running | wc -l
24
```
**7. Now, let's kill all the instances**
```bash
root@clr-ciao01 ~ # ciao-cli -delete-instance -all-instances
os-delete all instances for tenant b2d4c9355be54dd699f7ea9349997729
```
**8. After some reasonable time (~1min), we still have the pending VMs**
```bash
root@clr-ciao01 ~ # ciao-cli -list-instances | grep Status
        Status: pending
        Status: pending
        Status: pending
        .
        .
root@clr-ciao01 ~ # ciao-cli -list-instances | grep Status | wc -l
23
root@clr-ciao01 ~ # ciao-cli -list-instances | grep pending | wc -l
23
```

**Comment by kaccardi** [comment] 2016-05-03 00:25
@sameo @obedmr I have been making a requirement on deleting instances that they actually be instances that were exited or running.  Pending issues don't get deleted because they were never assigned to a node.  Previously I required a separate operation ("clean") to get rid of the pending ones.  Do you think this is a confusing distinction?  Or should we add a command to ciao-cli to clean up the pending instances?  Finally - should we review the flow following a "Cloud Full" message.  Right now we leave the instance as pending but never do anything to try to reschedule it (I don't think it's even possible).  Maybe we should delete it and just log an error.

**Comment by kaccardi** [comment] 2016-05-03 00:28
err - wait a minute - I just reviewed the StartFailure path and I should have already deleted the instance if the scheduler was sending StartFailure with Full Cloud reason.  So this seems like a bug somewhere that it's not actually getting deleted correctly.

**Comment by markdryan** [comment] 2016-05-03 09:37
Just one comment here.  Launcher also sets the status of VMs to pending.  It does this when it has launched the VM but has not yet detected that the VM has started.  The controller could easily receive a stats command from launcher with some instances states set to pending.  In this case the instances have been assigned to a node but haven't started yet.  Presumably we don't want to clean these guys up.

**Comment by kaccardi** [comment] 2016-05-07 00:04
after reviewing the code, I think this has got to be the case here - the ones left behind are the ones that the launcher marked as pending.  So, I think this is by design and not a bug.  Agree?

**Comment by kaccardi** [comment] 2016-05-16 22:45
I'm going to close this - we can reopen if you decide this is actually a bug

**Closed by kaccardi** 2016-05-16 22:45 UTC
