### ISSUE TITLE
Implement persistent data storage for ciao-image

### ISSUE THREAD

**Issue by kaccardi** [01org/ciao#384] opened 2016-07-20 17:14 UTC
Implement the ciao-image datastore interface to store data persistently.

**Comment by amyleeland** [comment] 2016-08-01 17:07
May not complete this Sprint

**Comment by markdryan** [comment] 2016-10-13 11:03
@kaccardi, @obedmr  Is this a duplicate of #632?

**Comment by obedmr** [comment] 2016-10-14 16:10
@kaccardi @markdryan I'd say yes, it's duplicated.

**Comment by obedmr** [comment] 2016-11-09 13:09
Implemented on #632

**Closed by obedmr** 2016-11-09 13:09 UTC
Labels: ciao-image, in progress, P1
