### ISSUE TITLE
Test plan for Volume attach/detach

### ISSUE THREAD

**Issue by chavafg** [01org/ciao#435] opened 2016-08-04 17:10 UTC
Need to create a test plan for this functionality.

**Comment by markdryan** [comment] 2016-10-14 14:22
I've made a start

https://github.com/01org/ciao/wiki/Testing-Storage

but we only have positive test cases here, and at least on use case is missing.  Also, there are no image services tests listed.

**Comment by markdryan** [comment] 2016-10-25 18:38
Duplicate of #682

**Closed by markdryan** 2016-10-25 18:38 UTC
Labels: ready, storage
