### ISSUE TITLE
Failed to start container: failed to add interface svp_ae86911 to sandbox

### ISSUE THREAD

**Issue by markdryan** [01org/ciao#34] opened 2016-04-14 15:40 UTC
```
I0414 15:19:53.285424   10726 network.go:282] CN VNIC created = svn_ae86911 &{2 sbr_3f2cf6ba {172.16.0.0 ffffff00} 172.16.0.1 br_8fa6d6ec08c444ed951b2c2018a4c6ad_172.16.0.0/24_902d35e7-d635-4000-91ba-dc76ef8ef389_192.168.0.118} &{2 192.168.0.118 192.168.0.83 172.16.0.0/24 8fa6d6ec08c444ed951b2c2018a4c6ad 172.16.0.0/24 902d35e7-d635-4000-91ba-dc76ef8ef389  4268 }
I0414 15:19:53.762754   10726 network.go:282] CN VNIC created = svn_ae86911 &{0 sbr_3f2cf6ba {172.16.0.0 ffffff00} 172.16.0.1 br_8fa6d6ec08c444ed951b2c2018a4c6ad_172.16.0.0/24_902d35e7-d635-4000-91ba-dc76ef8ef389_192.168.0.118} <nil>
E0414 15:19:54.201167   10726 docker.go:257] Unable to start container Error response from daemon: Cannot start container 0665d3cb511f9405f291dd4b43a1865e9bd69359bf5a280867d2fd9af2840aab: [9] System error: failed to add interface svp_ae86911 to sandbox: failed in prefunc: failed to get link by name "svp_ae86911": Link not found
E0414 15:19:54.201192   10726 instance.go:134] Unable to start instance[launch_failure]: Error response from daemon: Cannot start container 0665d3cb511f9405f291dd4b43a1865e9bd69359bf5a280867d2fd9af2840aab: [9] System error: failed to add interface svp_ae86911 to sandbox: failed in prefunc: failed to get link by name "svp_ae86911": Link not found
```

**Comment by kaccardi** [comment] 2016-04-20 17:03
are you still seeing this error?

**Comment by mcastelino** [comment] 2016-04-20 17:07
@markdryan this could be due to the same root cause as issue #44 basically a DHCP server failure to issue a lease to the CNCI.

**Comment by markdryan** [comment] 2016-04-20 21:32
@mcastelino  I'm not sure.  In this case the CNCI was correctly created and the controller had started to create CNs.  However, for some reason it tried to create two CNs with the same IP address.  I think if DHCP wasn't working the controller wouldn't have got this far.

@kaccardi This is actually a bug you reported to me last week.  I don't think anyone has seen it since last Thursday.  Perhaps it happens on the clusters where docker is using devicemapper.

**Comment by kaccardi** [comment] 2016-05-16 22:46
I think we should close this since nobody is seeing this bug anymore.

**Closed by kaccardi** 2016-05-16 22:46 UTC
Labels: bug, ciao-controller
