### ISSUE TITLE
cloud-init defaults are incorrect

### ISSUE THREAD

**Issue by mcastelino** [01org/ciao#113] opened 2016-05-10 19:19 UTC
https://github.com/01org/ciao/commit/3e7599f6bea1e1aecd7d15263b1e7bccf2ff7c6c
Seems to have broken clear cloud init.

invoking sudo causes following error
`>>> /etc/sudoers.d/users-cloud-init: syntax error near line 2 <<<`

**Comment by markdryan** [comment] 2016-05-11 09:28
The bug reported above has been fixed in commit a8d84c7 which simply reverts 3e7599f, however the problem is not really solved.

Now that we have reverted the patch sudo is broken on Fedora and Ubuntu VM images provisioned with the test.yaml file, but it does work with clear images.  Note that commit 3e7599f is actually correct.  The problem is with clear-cloud-init (https://github.com/clearlinux/clr-cloud-init/issues/11).  However, it's more important for us right now to have sudo working on clear as we use it for our CNCI VM images.  So we need to wait until this bug is fixed in clear-cloud-init and makes it into a clear release.  Then we can update our CNCI image and recommit 3e7599f.

In the short term we should add a separate test.yaml file for Ubuntu and Fedora and modify https://github.com/01org/ciao/blob/master/ciao-controller/tables/workload_template.csv to point to this file.  This way we can have sudo working on all our test images.

@albertomurillo  Do you want to do this?

**Comment by albertomurillo** [comment] 2016-05-18 22:11
The bug with clearlinux/clr-cloud-init is fixed.
We just need to update CIAO's CNCI VM image to one with clearlinux >= 8160
And reaply the patch

**Comment by kaccardi** [comment] 2016-06-06 15:09
@markdryan Can we close this bug then?

**Comment by markdryan** [comment] 2016-06-06 15:18
Yes.  @mcastelino fixed this in 6040c081762fce380b34494590a3e01d1448cdc4

**Closed by markdryan** 2016-06-06 15:18 UTC
Labels: bug, ciao-controller
