### ISSUE TITLE
If instance stays in pending state its storage is not cleaned up

### ISSUE THREAD

**Issue by erick0z** [01org/ciao#1079] opened 2017-01-27 23:41 UTC
If an instance is lost for some reason (left with a pending state for example), it happens that the child of the image’s snapshot in the rbd pool will be never deleted, leading to the inability to delete the image from the Ciao image service, unless the children of a given snapshot  are removed manually.
This issue is reproducible using 1Gb  Network setups, when the amount of requested resources surpasses the available resources(e.g. Launching a considerable amount of instances will cause this). Although it's reproducible with this setup, it's not exempt to happen under other, not yet known circumstances.

**Comment by rbradford** [comment] 2017-01-30 14:23
Okay, this is bad as we're leaking disk space too. 

This is probably caused by an error code path inside controller where we're not cleaning up ephemeral storage. Can you tell me what state the instances are in when this happens (ciao-cli instance list) and can you also attach the WARNING controller log.

**Comment by erick0z** [comment] 2017-01-31 16:39
Half of the deployed instances were in `pending` status and the remaining fields were in N/A. I couldn't reproduce the issue this morning, I suspect that when I was deploying the instances, the ceph cluster were under scrubbing/deep-scrubbing. I'll try to get the logs.

**Comment by rbradford** [comment] 2017-02-01 11:10
Thinking about this some more - I think that the underlying issue is that the instances are in the pending state for too long.

**Comment by kaccardi** [comment] 2017-02-16 17:37
@rbradford is this bug still an issue?

**Comment by rbradford** [comment] 2017-02-16 17:39
Reporter gave no way to reproduce. I think the behaviour is correct that volumes are held onto for instances in the pending state. So I think closing is the right course of action.

**Closed by rbradford** 2017-02-16 17:39 UTC
Labels: bug, P2
