### ISSUE TITLE
ciao-cli does not correctly list volume details

### ISSUE THREAD

**Issue by kaccardi** [01org/ciao#497] opened 2016-08-29 20:39 UTC
When multiple volumes are created - some with name and description and some without, ciao-cli doesn't display the name and description.

**Comment by kaccardi** [comment] 2016-08-29 20:43
the problem is intermittent unfortunately.

**Comment by kaccardi** [comment] 2016-08-30 00:04
quite possibly this is a gopherclient bug.

**Comment by markdryan** [comment] 2016-10-14 14:12
This code be a duplicate of #644

**Closed** 2016-10-25 17:31 UTC
Labels: bug, ciao-cli, P2, storage drivers
